// The single ESLint config for the whole workspace. Every member is linted from
// here: per-package configs would drift, which AGENTS.md bans.
//
// Type-aware rules read the generated src/managed/ types, so `yarn compile`
// must run before `yarn lint`, the same ordering `yarn build` needs.
//
// The config turns NO rule off. When a rule fires, the code gets fixed. A
// config fitted to the code that happens to exist licenses the same defect
// forever; one that turns nothing off is a standard the code is held to.

import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import prettier from "eslint-config-prettier/flat";
import importX from "eslint-plugin-import-x";
import jsdoc from "eslint-plugin-jsdoc";
import jsxA11y from "eslint-plugin-jsx-a11y";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

/**
 * Package specifiers that reach by name into a package's SOURCE tree to read
 * its generated compiler output, which AGENTS.md prohibits from outside the
 * owning package.
 *
 * The packaged `./managed/*` subpath is deliberately absent: both this repo's
 * contract packages and `@sig-net/midnight-contract` declare it in `exports`,
 * so it is a published API. The simulator tests import the signet contract
 * module through it to execute the cross-contract call path.
 *
 * A RELATIVE path into another package's output is `import-x/no-relative-packages`' catch.
 */
const MANAGED_DEEP_IMPORTS = ["@midnight-examples/*/src/managed/**", "@sig-net/*/src/managed/**"];

export default defineConfig([
  // Only generated output that ESLint would otherwise lint. node_modules is
  // ignored by default, and the other gitignored dirs (.yarn, reports, logs,
  // midnight-level-db) hold no JS or TS.
  globalIgnores([
    // compactc output, regenerated by `yarn compile` and gitignored. The glob
    // also covers the src/managed/SignetSigner symlink into the SDK's own
    // managed output, which otherwise walks a file crawler into node_modules.
    "**/src/managed/**",
    // hardhat solc output: absent until `yarn compile:evm` runs.
    "examples/*/integration-tests/artifacts/**",
    "examples/*/integration-tests/cache/**",
    // a ui member's Vite bundle: a gitignored deploy artefact, absent until
    // `yarn build` runs.
    "examples/*/ui/dist/**",
  ]),

  {
    name: "workspace/typescript",
    files: ["**/*.ts", "**/*.tsx"],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        // The TypeScript project service resolves each file against its own
        // package's nearest tsconfig.json, so a workspace needs no enumerated
        // project list and no tsconfig.eslint.json.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    plugins: {
      "import-x": importX,
      "simple-import-sort": simpleImportSort,
    },
    rules: {
      // tsconfig.base.json sets verbatimModuleSyntax, which makes the type-only
      // marker load-bearing rather than cosmetic: an unmarked type import is
      // emitted as a real runtime import.
      "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
      "@typescript-eslint/no-import-type-side-effects": "error",

      // Matches tsc's noUnusedLocals/noUnusedParameters, which already exempt
      // the underscore prefix.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      "import-x/no-relative-packages": "error",
      "no-restricted-imports": ["error", { patterns: MANAGED_DEEP_IMPORTS }],

      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
    },
  },

  {
    name: "workspace/jsdoc",
    files: ["**/src/**/*.ts", "**/src/**/*.tsx", "**/deploy.ts"],
    extends: [jsdoc.configs["flat/recommended-typescript-error"]],
    rules: {
      // Every export carries a block. Internal helpers are the author's call.
      "jsdoc/require-jsdoc": [
        "error",
        {
          publicOnly: true,
          require: {
            ArrowFunctionExpression: true,
            ClassDeclaration: true,
            ClassExpression: true,
            FunctionDeclaration: true,
            FunctionExpression: true,
            MethodDefinition: true,
          },
          contexts: [
            "TSEnumDeclaration",
            "TSInterfaceDeclaration",
            "TSTypeAliasDeclaration",
            "TSMethodSignature",
            // Exported consts only. A bare VariableDeclaration selector also
            // matches locals inside function bodies, where this plugin's
            // autofixer inserts syntactically broken blocks.
            "ExportNamedDeclaration > VariableDeclaration",
          ],
        },
      ],
      "jsdoc/require-throws": "error",
      // The house style separates the description from the first tag with one
      // blank line.
      "jsdoc/tag-lines": ["error", "any", { startLines: 1 }],
    },
  },

  // The react rule set, scoped to where react code lives: a ui member's own
  // tree (components, hooks and their tests — hooks-in-.ts included, so the
  // rules of hooks reach useX() helpers that render nothing). Three plugins:
  // react's recommended set on the modern JSX runtime, the rules of hooks,
  // and jsx-a11y (the tests already query by role and accessible name, so
  // the markup is held to the same standard).
  //
  // eslint-plugin-react-refresh is deliberately NOT part of the set. Its
  // only-export-components rule is incompatible with two conventions this
  // repo keeps on purpose: a context file co-locating its provider, hook and
  // errors, and shadcn/ui registry output exporting cva variants beside the
  // component. Adopting it would mean restructuring both away from their
  // documented shapes; the price of leaving it out is only that vite HMR
  // falls back to a full reload when those files change.
  {
    name: "workspace/react",
    files: ["examples/*/ui/src/**/*.{ts,tsx}", "examples/*/ui/tests/**/*.{ts,tsx}"],
    extends: [
      react.configs.flat.recommended,
      react.configs.flat["jsx-runtime"],
      reactHooks.configs.flat["recommended-latest"],
      jsxA11y.flatConfigs.recommended,
    ],
    settings: {
      // Not "detect": detection resolves react from the config's own
      // directory, and react is a ui member's dependency, not the root's.
      // Keep in lockstep with the react version in examples/*/ui/package.json.
      react: { version: "19.2" },
    },
    rules: {
      // shadcn/ui's Input and Checkbox render a real <input> / <button
      // role="checkbox">, both labelable; the rule cannot see through a
      // custom component, so it is told which ones are controls. A widening
      // of what the rule recognises, not an exemption from it.
      "jsx-a11y/label-has-associated-control": [
        "error",
        { controlComponents: ["Input", "Checkbox"] },
      ],
    },
  },
  {
    name: "workspace/tests",
    files: ["**/tests/**/*.ts", "**/tests/**/*.tsx", "**/*.test.ts", "**/*.test.tsx"],
    extends: [vitest.configs.recommended],
    rules: {
      // An it.only reaching main silently disables the rest of its suite.
      "vitest/no-focused-tests": "error",
      // expectTypeOf is vitest's type-level assertion. Registering it is not a
      // relaxation: the rule's default list simply predates the API.
      "vitest/expect-expect": ["error", { assertFunctionNames: ["expect", "expectTypeOf"] }],
    },
  },

  // This file itself. No disableTypeChecked needed: the type-aware configs are
  // scoped to .ts/.tsx files, so they never reach a .js file.
  {
    name: "workspace/config-files",
    files: ["**/*.js", "**/*.mjs"],
    extends: [js.configs.recommended],
  },

  // Last: turns off every rule that would fight Prettier.
  prettier,
]);
