import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, unlinkSync } from "node:fs";
import { join, resolve } from "node:path";

import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { generateHexSeed, getMidnightNodeConfig } from "@sig-net/midnight-contract-deploy";
import { readVaultLedger } from "@sig-net/midnight-examples-erc20-vault-contract";
import { parseDotEnv, REPO_ROOT } from "@sig-net/midnight-examples-lib";
import {
  ensureAnvilEthBalance,
  executeSetupPipeline,
  requireEnv,
  type SetupStep,
  writePrivate,
} from "@sig-net/midnight-examples-lib";
import { JsonRpcProvider, Wallet } from "ethers";

import { initialiseVault } from "./initialise-vault.ts";
import { verifyLocalArtifacts } from "./local-artifacts.ts";
import { vaultSetupSteps } from "./setup-vault.ts";

/** Local stack identity persisted before any deployment. */
interface LocalStackIdentity {
  instanceId: string;
  markerAddress: string;
  markerCode: string;
}

/**
 * Deploy and initialise a local vault and export the browser and funding configuration.
 *
 * @param input - Environment read by the CLI or integration caller.
 * @param uiDirectory - UI checkout receiving .env.local.
 * @returns The prepared deployment environment.
 * @throws {Error} When the endpoint is ineligible, the stack identity changed or preparation fails.
 */
export async function setupLocalVault(
  input: NodeJS.ProcessEnv,
  uiDirectory: string,
): Promise<NodeJS.ProcessEnv> {
  const target = join(resolve(uiDirectory), ".env.local");
  const header = "# Generated by setup-local:erc20-vault\n";
  if (existsSync(target) && !readFileSync(target, "utf8").startsWith(header))
    throw new Error(
      "UI .env.local is user-owned. Move it to a private backup before generating local configuration.",
    );
  verifyLocalArtifacts(uiDirectory);
  const env: NodeJS.ProcessEnv = { ...input };
  env.MIDNIGHT_NETWORK_ID = "undeployed";
  env.EVM_RPC_URL = "http://127.0.0.1:8545";
  env.MIDNIGHT_NODE_URL = "http://127.0.0.1:9944";
  env.MIDNIGHT_INDEXER_URL = "http://127.0.0.1:8088/api/v3/graphql";
  env.MIDNIGHT_INDEXER_WS_URL = "ws://127.0.0.1:8088/api/v3/graphql/ws";
  env.MIDNIGHT_PROOF_SERVER_URL = "http://127.0.0.1:6300";
  env.FAKENET_EVM_RPC_URL = "http://evm:8545";
  delete env.SEPOLIA_FORK_RPC_URL;
  const directory = join(REPO_ROOT, ".local-demo");
  mkdirSync(directory, { recursive: true, mode: 0o700 });
  const privateEnvironmentPath = join(directory, "setup.env");
  const saved = existsSync(privateEnvironmentPath)
    ? parseDotEnv(readFileSync(privateEnvironmentPath, "utf8"))
    : {};
  for (const [key, value] of Object.entries(saved)) {
    if (env[key] !== undefined && env[key] !== value)
      throw new Error(
        `Saved local configuration conflicts with ${key}. Restore its generated value or prepare a fresh stack configuration.`,
      );
    env[key] = value;
  }
  const generatedKeys = [
    "ROOT_SEED",
    "DEPLOYER_SEED",
    "USER_SEED",
    "MPC_RESPONDER_SEED",
    "BEARER_SEED",
    "VAULT_USER_SECRET_KEY",
    "VAULT_DEPLOYER_SECRET_KEY",
    "RELAYER_PRIVATE_KEY",
    "MPC_ROOT_KEY",
    "MPC_SECP256K1_PUBKEY",
    "MPC_RESPONSE_KEY",
    "MIDNIGHT_SIGNET_CONTRACT_ADDRESS",
    "MIDNIGHT_VAULT_CONTRACT_ADDRESS",
    "EVM_CHAIN_ID",
    "EVM_USER_ADDRESS",
    "EVM_VAULT_ADDRESS",
    "ERC20_ADDRESS",
  ];
  const checkpoint = (): void => {
    writePrivate(
      privateEnvironmentPath,
      generatedKeys
        .filter((key) => env[key] !== undefined)
        .map((key) => `${key}=${requireEnv(env, key)}`)
        .join("\n") + "\n",
    );
  };
  const provider = new JsonRpcProvider(env.EVM_RPC_URL);
  try {
    const info = (await provider.send("anvil_metadata", [])) as {
      instanceId?: string;
      forkConfig?: { forkChainId?: number };
    };
    if (typeof info.instanceId !== "string" || (await provider.getNetwork()).chainId !== 11155111n)
      throw new Error("Setup requires a local Anvil Sepolia fork on port 8545.");
    const identityPath = join(directory, "instance.json");
    const identity: LocalStackIdentity = existsSync(identityPath)
      ? (JSON.parse(readFileSync(identityPath, "utf8")) as LocalStackIdentity)
      : {
          instanceId: info.instanceId,
          markerAddress: `0x${randomBytes(20).toString("hex")}`,
          markerCode: `0x${randomBytes(32).toString("hex")}`,
        };
    if (identity.instanceId !== info.instanceId)
      throw new Error(
        "Anvil stack identity changed. Keep the running services and remove the generated deployment configuration before preparing this fresh stack. Do not reuse its former addresses.",
      );
    if (!existsSync(identityPath)) {
      await provider.send("anvil_setCode", [identity.markerAddress, identity.markerCode]);
      writePrivate(identityPath, JSON.stringify(identity));
    }
    if ((await provider.getCode(identity.markerAddress)) !== identity.markerCode)
      throw new Error(
        "Local fork marker is missing. The stack state changed, so its generated configuration cannot be reused.",
      );
    const configuration = getMidnightNodeConfig(env);
    const existingData = indexerPublicDataProvider({
      queryURL: configuration.indexerUrl,
      subscriptionURL: configuration.indexerWsUrl,
    });
    try {
      for (const key of ["MIDNIGHT_SIGNET_CONTRACT_ADDRESS", "MIDNIGHT_VAULT_CONTRACT_ADDRESS"]) {
        const address = env[key];
        if (address && !(await existingData.queryContractState(address)))
          throw new Error(
            `Saved ${key} is absent from Midnight. The local chain changed, so reset the generated deployment configuration before setup.`,
          );
      }
    } finally {
      await existingData.dispose();
    }
    env.VAULT_USER_SECRET_KEY ??= generateHexSeed();
    env.RELAYER_PRIVATE_KEY ??= Wallet.createRandom().privateKey;
    checkpoint();
    env.TRUST_PREBUILT_ZK_KEYS = "1";
    const steps = vaultSetupSteps().map(
      ([name, run]) =>
        [
          name,
          async (stepEnv, wallets) => {
            await run(stepEnv, wallets);
            checkpoint();
          },
        ] as const satisfies SetupStep,
    );
    await executeSetupPipeline(env, steps);
    await initialiseVault(env);
    const relayer = new Wallet(requireEnv(env, "RELAYER_PRIVATE_KEY"));
    await ensureAnvilEthBalance(provider, relayer.address, 10n ** 18n);
    const config = getMidnightNodeConfig(env);
    const publicData = indexerPublicDataProvider({
      queryURL: config.indexerUrl,
      subscriptionURL: config.indexerWsUrl,
    });
    try {
      const vault = await readVaultLedger(
        publicData,
        requireEnv(env, "MIDNIGHT_VAULT_CONTRACT_ADDRESS"),
      );
      if (!vault.initialised)
        throw new Error("Vault initialisation is not visible through the local indexer.");
    } finally {
      await publicData.dispose();
    }
    writePrivate(
      privateEnvironmentPath,
      generatedKeys.map((key) => `${key}=${requireEnv(env, key)}`).join("\n") + "\n",
    );
    writePrivate(
      join(directory, "testing-user.env"),
      `MIDNIGHT_USER_SEED=${requireEnv(env, "USER_SEED")}\nVAULT_CALLER_SECRET=${requireEnv(env, "VAULT_USER_SECRET_KEY")}\n`,
    );
    const generatedValues: Record<string, string> = {
      NEXT_PUBLIC_SEPOLIA_RPC_URL: requireEnv(env, "EVM_RPC_URL"),
      NEXT_PUBLIC_MIDNIGHT_NETWORK_ID: "undeployed",
      NEXT_PUBLIC_MIDNIGHT_NODE_URL: requireEnv(env, "MIDNIGHT_NODE_URL"),
      NEXT_PUBLIC_MIDNIGHT_INDEXER_URL: requireEnv(env, "MIDNIGHT_INDEXER_URL"),
      NEXT_PUBLIC_MIDNIGHT_INDEXER_WS_URL: requireEnv(env, "MIDNIGHT_INDEXER_WS_URL"),
      NEXT_PUBLIC_MIDNIGHT_PROOF_SERVER_URL: requireEnv(env, "MIDNIGHT_PROOF_SERVER_URL"),
      NEXT_PUBLIC_MIDNIGHT_CONTRACT_ADDRESS: requireEnv(env, "MIDNIGHT_VAULT_CONTRACT_ADDRESS"),
      NEXT_PUBLIC_MIDNIGHT_SIGNET_CONTRACT_ADDRESS: requireEnv(
        env,
        "MIDNIGHT_SIGNET_CONTRACT_ADDRESS",
      ),
      NEXT_PUBLIC_MPC_SECP256K1_PUBKEY: requireEnv(env, "MPC_SECP256K1_PUBKEY"),
      NEXT_PUBLIC_LOCAL_EVM_MARKER_ADDRESS: identity.markerAddress,
      NEXT_PUBLIC_LOCAL_EVM_MARKER_CODE: identity.markerCode,
      LOCAL_ANVIL_INSTANCE_ID: identity.instanceId,
      LOCAL_MIDNIGHT_GENESIS_SEED: requireEnv(env, "ROOT_SEED"),
      RELAYER_PRIVATE_KEY: requireEnv(env, "RELAYER_PRIVATE_KEY"),
    };
    writePrivate(
      target,
      header +
        Object.entries(generatedValues)
          .map(([key, value]) => `${key}=${value}`)
          .join("\n") +
        "\n",
    );
    return env;
  } finally {
    provider.destroy();
  }
}

/**
 * Clear only generated chain-bound values after a verified local chain reset.
 *
 * @throws {Error} When the stack is still current or saved configuration conflicts with .env.
 */
export async function resetLocalConfiguration(): Promise<void> {
  const directory = join(REPO_ROOT, ".local-demo");
  const identityPath = join(directory, "instance.json");
  const savedPath = join(directory, "setup.env");
  const identity = JSON.parse(readFileSync(identityPath, "utf8")) as LocalStackIdentity;
  const saved = parseDotEnv(readFileSync(savedPath, "utf8"));
  const provider = new JsonRpcProvider("http://127.0.0.1:8545");
  try {
    const metadata = (await provider.send("anvil_metadata", [])) as { instanceId?: string };
    if (typeof metadata.instanceId !== "string")
      throw new Error("Local Anvil metadata is unavailable.");
    let stale = metadata.instanceId !== identity.instanceId;
    const publicData = indexerPublicDataProvider({
      queryURL: "http://127.0.0.1:8088/api/v3/graphql",
      subscriptionURL: "ws://127.0.0.1:8088/api/v3/graphql/ws",
    });
    try {
      for (const key of ["MIDNIGHT_SIGNET_CONTRACT_ADDRESS", "MIDNIGHT_VAULT_CONTRACT_ADDRESS"]) {
        const address = saved[key];
        if (address && !(await publicData.queryContractState(address))) stale = true;
      }
    } finally {
      await publicData.dispose();
    }
    if (!stale)
      throw new Error(
        "The saved local stack is still current. Rerun setup without --reset-config to reuse it.",
      );
    const chainKeys = new Set([
      "MIDNIGHT_SIGNET_CONTRACT_ADDRESS",
      "MIDNIGHT_VAULT_CONTRACT_ADDRESS",
      "MPC_RESPONSE_KEY",
      "EVM_USER_ADDRESS",
      "EVM_VAULT_ADDRESS",
    ]);
    const environmentPath = join(REPO_ROOT, ".env");
    const environmentText = readFileSync(environmentPath, "utf8");
    const environment = parseDotEnv(environmentText);
    for (const key of chainKeys)
      if (environment[key] !== undefined && environment[key] !== saved[key])
        throw new Error(
          `User-owned ${key} conflicts with the saved setup. Reconcile it before resetting generated configuration.`,
        );
    const backup = join(directory, `before-reset-${String(Date.now())}`);
    mkdirSync(backup, { mode: 0o700 });
    writePrivate(join(backup, "environment.env"), environmentText);
    writePrivate(join(backup, "setup.env"), readFileSync(savedPath, "utf8"));
    writePrivate(join(backup, "instance.json"), JSON.stringify(identity));
    const retained = Object.fromEntries(
      Object.entries(saved).filter(([key]) => !chainKeys.has(key)),
    );
    writePrivate(
      savedPath,
      Object.entries(retained)
        .map(([key, value]) => `${key}=${value}`)
        .join("\n") + "\n",
    );
    writePrivate(
      environmentPath,
      environmentText
        .split("\n")
        .filter((line) => !chainKeys.has(/^\s*([A-Z_]+)=/.exec(line)?.[1] ?? ""))
        .join("\n"),
    );
    if (metadata.instanceId === identity.instanceId)
      await provider.send("anvil_setCode", [identity.markerAddress, "0x"]);
    unlinkSync(identityPath);
  } finally {
    provider.destroy();
  }
}
