// One config serves both the bundler and the test runner: `defineConfig` comes
// from vitest/config so the `test` block is typed, and `vite build` ignores it.
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { normalizePath } from "vite";
import { viteStaticCopy } from "vite-plugin-static-copy";
import { defineConfig } from "vitest/config";

// Absolute because the copy plugin's globs cannot traverse ".." upwards.
const contractManagedDir = normalizePath(
  new URL("../contract/src/managed", import.meta.url).pathname,
);

// The workspace's hoisted node_modules, for the polyfill aliases below.
const rootNodeModules = normalizePath(new URL("../../../node_modules", import.meta.url).pathname);

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // Expose the contract package's compiled zk assets (keys/, zkir/) under
    // BASE_URL/managed/<contract>/ for FetchZkConfigProvider. The managed
    // output is regenerated by the contract package's compile script, so it
    // is served from its source location in `vite dev` (never stale) and only
    // copied into dist/ by `vite build`. The glob also picks up SignetSigner
    // (the symlinked signet callee output) for cross-contract proving.
    viteStaticCopy({
      targets: [
        // The copy destination mirrors the matched path relative to this
        // package ("contract/src/managed/<contract>/..."), so stripBase: 3
        // drops the "contract/src/managed" prefix and each contract's output
        // lands at managed/<contract>/keys|zkir/... exactly as
        // FetchZkConfigProvider expects.
        {
          src: `${contractManagedDir}/erc20-vault`,
          dest: "managed",
          rename: { stripBase: 3 },
        },
        {
          src: `${contractManagedDir}/SignetSigner`,
          dest: "managed",
          rename: { stripBase: 3 },
        },
      ],
    }),
  ],
  resolve: {
    alias: {
      // The "@/" alias shadcn/ui generates its imports against, declared for
      // the compiler in tsconfig.json's paths. Resolved off import.meta.url
      // rather than node:path so this config needs no @types/node.
      "@": normalizePath(new URL("./src", import.meta.url).pathname),
      // Node builtins two of the private-state store's dependencies import:
      // abstract-level extends `events`' EventEmitter at module scope, and
      // @subsquid/scale-codec (via midnight-js-utils) asserts with `assert`.
      // Vite only warns ("externalized for browser compatibility") and stubs
      // them, which crashes at runtime in the browser. `events` is pinned to
      // its npm polyfill (an absolute path: a bare same-name replacement
      // would re-enter the alias); `assert` gets the one owned function the
      // callers actually use, since the npm assert polyfill reads
      // `process.env` at module scope and crashes the page itself. Extend
      // this list ONLY on the same evidence, a new externalized-module
      // warning from `vite build`, and prefer the smallest shim that
      // satisfies the real call sites.
      events: `${rootNodeModules}/events/events.js`,
      assert: normalizePath(new URL("./src/lib/polyfills/assert.ts", import.meta.url).pathname),
    },
  },
  server: {
    port: 5173,
  },
  optimizeDeps: {
    // These packages' wasm-bindgen glue is a pair of circularly-importing ESM
    // modules; esbuild pre-bundling breaks that cycle and every import then
    // dies in dev ("Cannot access '__wbindgen_start' before initialization" /
    // "Cannot read properties of undefined (reading '__wbindgen_export_2')")
    // while vite build bundles them correctly. Serving them unbundled keeps
    // the native ESM evaluation order the glue relies on.
    exclude: ["@midnightntwrk/ledger-v9", "@midnightntwrk/onchain-runtime-v4"],
  },
  build: {
    // A tripwire for a dependency quietly bloating first paint, NOT a hard
    // gate: vite only warns past this and still exits 0, so it catches the
    // next unnoticed jump rather than preventing one.
    //
    // Raised from 600 when the shadcn/ui runtime arrived and put the entry
    // chunk at ~660 kB (~180 kB gzipped). Attributed with the build's own
    // sourcemap, the additions are tailwind-merge, sonner, @radix-ui/react-menu
    // and floating-ui, roughly 160 kB between them. radix-ui and lucide-react
    // both tree-shake: only the menu primitive and the icons actually used
    // reach the bundle. Move this number again only alongside the same
    // measurement, and say what pushed it.
    //
    // Raised again from 800 when the vault context became reachable from App
    // (the deposit-address step) and put the entry chunk at ~1620 kB (~440 kB
    // gzipped): the compiled contract plus compact-js and compact-runtime,
    // @sig-net/midnight's ethers + @noble/curves, the level private-state
    // store, and TanStack Query. The two wasm blobs are separate assets and
    // never counted here.
    // Raised again from 1700 when the vault-interaction step started reading
    // balances and put the entry chunk at ~1746 kB (~481 kB gzipped), up from
    // ~1632 kB (~448 kB): viem's public actions and its ABI encode/decode path
    // were not reachable before, since nothing had yet read from the EVM
    // chain. viem's own lazy paths (ccip, the batch gateway, secp256k1) split
    // out into separate chunks and are not in this number.
    chunkSizeWarningLimit: 1800,
    sourcemap: true,
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./tests/setup.ts"],
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
    // The deposit-address tests chain several genuinely slow operations
    // (wallet signing, the store's password key derivation, circuit calls),
    // each already allowed up to 5s by the Testing Library timeout raised in
    // tests/setup.ts: the per-test budget must fit a few of them in sequence.
    testTimeout: 20_000,
    env: {
      // A valid MPC root key for tests, so deposit addresses derive: the
      // secp256k1 generator point (the public key of secret 1), well known
      // and never holding value. Any valid point would do.
      VITE_MPC_SECP256K1_PUBKEY:
        "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
    },
    // The private-state store note: vitest resolves `level` with Node's
    // rules (no `browser` condition), so tests run it on classic-level,
    // which writes a real ./midnight-level-db directory at the current
    // working directory. tests/setup.ts gives every test its own tmp
    // working directory to keep those stores isolated. The browser backend
    // is no alternative here: vitest's jsdom realm split breaks
    // browser-level's binary encoding checks and corrupts what it stores.
  },
});
