// One config serves both the bundler and the test runner: `defineConfig` comes
// from vitest/config so the `test` block is typed, and `vite build` ignores it.
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { normalizePath } from "vite";
import { viteStaticCopy } from "vite-plugin-static-copy";
import { defineConfig } from "vitest/config";

// Absolute because the copy plugin's globs cannot traverse ".." upwards.
const contractManagedDir = normalizePath(
  new URL("../contract/src/managed", import.meta.url).pathname,
);

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // Expose the contract package's compiled zk assets (keys/, zkir/) under
    // BASE_URL/managed/<contract>/ for FetchZkConfigProvider. The managed
    // output is regenerated by the contract package's compile script, so it
    // is served from its source location in `vite dev` (never stale) and only
    // copied into dist/ by `vite build`. The glob also picks up SignetSigner
    // (the symlinked signet callee output) for cross-contract proving.
    viteStaticCopy({
      targets: [
        // The copy destination mirrors the matched path relative to this
        // package ("contract/src/managed/<contract>/..."), so stripBase: 3
        // drops the "contract/src/managed" prefix and each contract's output
        // lands at managed/<contract>/keys|zkir/... exactly as
        // FetchZkConfigProvider expects.
        {
          src: `${contractManagedDir}/erc20-vault`,
          dest: "managed",
          rename: { stripBase: 3 },
        },
        {
          src: `${contractManagedDir}/SignetSigner`,
          dest: "managed",
          rename: { stripBase: 3 },
        },
      ],
    }),
  ],
  resolve: {
    alias: {
      // The "@/" alias shadcn/ui generates its imports against, declared for
      // the compiler in tsconfig.json's paths. Resolved off import.meta.url
      // rather than node:path so this config needs no @types/node.
      "@": normalizePath(new URL("./src", import.meta.url).pathname),
    },
  },
  server: {
    port: 5173,
  },
  optimizeDeps: {
    // These packages' wasm-bindgen glue is a pair of circularly-importing ESM
    // modules; esbuild pre-bundling breaks that cycle and every import then
    // dies in dev ("Cannot access '__wbindgen_start' before initialization" /
    // "Cannot read properties of undefined (reading '__wbindgen_export_2')")
    // while vite build bundles them correctly. Serving them unbundled keeps
    // the native ESM evaluation order the glue relies on.
    exclude: ["@midnightntwrk/ledger-v9", "@midnightntwrk/onchain-runtime-v4"],
  },
  build: {
    // A tripwire for a dependency quietly bloating first paint, NOT a hard
    // gate: vite only warns past this and still exits 0, so it catches the
    // next unnoticed jump rather than preventing one.
    //
    // Raised from 600 when the shadcn/ui runtime arrived and put the entry
    // chunk at ~660 kB (~180 kB gzipped). Attributed with the build's own
    // sourcemap, the additions are tailwind-merge, sonner, @radix-ui/react-menu
    // and floating-ui, roughly 160 kB between them. radix-ui and lucide-react
    // both tree-shake: only the menu primitive and the icons actually used
    // reach the bundle. Move this number again only alongside the same
    // measurement, and say what pushed it.
    chunkSizeWarningLimit: 800,
    sourcemap: true,
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./tests/setup.ts"],
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
  },
});
